# Generated by Django 3.2.3 on 2021-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranswer',
            name='custom_answer',
            field=models.ManyToManyField(blank=True, null=True, related_name='selected_answers_option', to='api.AnswersOption'),
        ),
    ]
