# Generated by Django 3.2 on 2021-05-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210331_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='test project', max_length=150, null=True, verbose_name='Название Проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.TextField(blank=True, choices=[('Django', 'Django'), ('Java Spring', 'Javaspring'), ('PHP', 'Php'), ('JavaAndroid', 'Javaandroid'), ('Swift', 'Swift')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.customer'),
        ),
    ]
