# Generated by Django 3.2.3 on 2021-06-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Тег (Суть)'),
        ),
    ]
