# Generated by Django 3.2 on 2021-05-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210526_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('name', models.CharField(default='Django', max_length=150, primary_key=True, serialize=False, verbose_name='Название технологии')),
                ('avg_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.stack'),
        ),
    ]
