# Generated by Django 3.2.3 on 2021-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210526_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='avg_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
