version: '3.3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
  django:
    build:
      context: .
      dockerfile: docker/DockerfileBackend
    container_name: backend
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
#  vue:
#    build:
#      context: .
#      dockerfile: docker/DockerfileFrontend
#    container_name: frontend
#    command: ./docker/frontend_setup.sh
#    volumes:
#      - .:/app
#    ports:
#      - "8082:8080"
#    depends_on:
#      - django
