version: '3.3'

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - "5432:5432"
  django:
    build:
      context: .
      dockerfile: docker/DockerfileBackend
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
#  vue:
#    build:
#      context: .
#      dockerfile: docker/DockerfileFrontend
#    container_name: frontend
#    command: ./docker/frontend_setup.sh
#    volumes:
#      - .:/app
#    ports:
#      - "8082:8080"
#    depends_on:
#      - django

volumes:
  postgres_data:

